server:
  port: 8080
spring:
  redis:
    host: 192.168.138.128
    port: 6379
    password: 123456
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.138.128:3306/reggie?useSSL=false
    username: root
    password: prynnekey
  application:
    # 应用的名称，可选
    name: reggie_take_out
  cache:
    redis:
      # 缓存过期时间，单位ms
      time-to-live: 1800000
  mvc:
    pathmatch:
      # 地址：https://blog.csdn.net/Java_web12138667/article/details/123168600
      # 解决加入swagger的异常 knife4j-spring-boot-starter
      # 异常场景：springboot2.6.x 搭配 springfox 3.0.0
      # 出现原因：springfox 3.0.0 错误导致
      matching-strategy: ant_path_matcher
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    # 表名：address_book ---> AddressBook
    # 字段名：user_name ----> userName
    # 在映射实体或者属性时，将数据库中的表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

reggie:
  upload:
    path: /usr/local/javaapp/img/